apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  # You'll usually want to add your resources to the argocd namespace.
  namespace: default
  # Add a this finalizer ONLY if you want these to cascade delete.
spec:
  # The project the application belongs to.
  project: default
  # Source of the application manifests
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: nginx-manifests

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy: {}