namespace:
  name: demo
 
image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  limits:
    cpu: "50m"
    memory: "256Mi"

service:
  port: "8111"
  type: "ClusterIP"

configmap:
  data: "version: alpine"
